Cypress.Commands.add('fillMandatoryFieldsAndSubmit', function() {
    cy.get('#firstName')
            .type('Bruce')
    cy.get('#lastName')
            .type('Wayne')
    cy.get('#email')
            .type('bruce.wayne@batman.com')
    cy.get('#open-text-area')
            .type('Testando o funcionamento')
    cy.get('.button')
            .click()
})